const youtubeChannelsData = [
  {
    title: "Coding Joy",
    summary: "Coding tutorials and programming insights.",
    description: "Coding tutorials and programming insights.",
    url: "https://youtube.com/@codingjoy",
    srcLight: "/youtube-color.png",
    srcDark: "/youtube-light.png",
    icon: "Code",
    color: "text-bright-blue",
  },
  {
    title: "Python Joy",
    summary: "Python programming tutorials and projects.",
    description: "Python programming language tutorials and projects.",
    url: "https://youtube.com/@pythonjoy",
    srcLight: "/youtube-color.png",
    srcDark: "/youtube-light.png",
    icon: "Book",
    color: "text-bright-green",
  },
  {
    title: "Python Tip",
    summary: "Python programming tips and tricks.",
    description: "Python programming tips and tricks.",
    url: "https://youtube.com/@pythontip",
    srcLight: "/youtube-color.png",
    srcDark: "/youtube-light.png",
    icon: "Lightbulb",
    color: "text-bright-purple",
  },
  {
    title: "AI Codin'",
    summary: "AI, ML, and LLM tutorials.",
    description: "Tutorials on artificial intelligence, machine learning, and large language models.",
    url: "https://youtube.com/@aicodin",
    srcLight: "/youtube-color.png",
    srcDark: "/youtube-light.png",
    icon: "Brain",
    color: "text-bright-orange",
  },
  {
    title: "Nutty Physics",
    summary: "Exploring the wonders of physics.",
    description: "Exploring the wonders of physics.",
    url: "https://youtube.com/@nuttyphysics",
    srcLight: "/youtube-color.png",
    srcDark: "/youtube-light.png",
    icon: "Zap",
    color: "text-bright-blue",
  },
  {
    title: "Einstein's Books",
    summary: "Relativity by Einstein.",
    description: "Learn special and general relativity using Einstein's books.",
    url: "https://youtube.com/@einsteinsbooks",
    srcLight: "/youtube-color.png",
    srcDark: "/youtube-light.png",
    icon: "Atom",
    color: "text-bright-green",
  },
  {
    title: "Typescript Joy",
    summary: "Typescript programming tutorials and projects.",
    description: "Typescript programming language tutorials and projects.",
    url: "https://youtube.com/@typescriptjoy",
    srcLight: "/youtube-color.png",
    srcDark: "/youtube-light.png",
    icon: "FileCode",
    color: "text-bright-purple",
  },
  {
    title: "Rust Joy",
    summary: "Rust programming tutorials and projects.",
    description: "Rust programming language tutorials and projects.",
    url: "https://youtube.com/@rustjoy",
    srcLight: "/youtube-color.png",
    srcDark: "/youtube-light.png",
    icon: "Shield",
    color: "text-bright-orange",
  },
];

export default youtubeChannelsData;
