name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch like 'master'
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (if needed for build)
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your required Node.js version

      - name: Install dependencies and build site (if needed)
        run: |
          npm install
          npm run build:all
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4




